include:
  -
    path:
      - vendor/johnbillion/plugin-infrastructure/tests/docker-compose.yml
      - tests/_support/MUPlugin/acceptance.yml
    project_directory: .

services:
  httpbin:
    image: mccutchen/go-httpbin:latest
    container_name: ${COMPOSE_PROJECT_NAME}-httpbin
    restart: always
    environment:
      PORT: 80
