/* eslint-disable */

/**
 * This file is generated by the build-schemas script.
 * Do not edit it manually.
 */

import {
	WP_Block_Template,
	WP_Error,
	WP_Network,
	WP_Post_Type,
	WP_Post,
	WP_Screen,
	WP_Site,
	WP_Term,
	WP_User,
} from 'wp-types';

export interface DataTypes {
	admin: AbstractData & Admin;
	assets_scripts: AbstractData & Assets;
	assets_styles: AbstractData & Assets;
	block_editor: AbstractData & Block_Editor;
	cache: AbstractData & Cache;
	caps: AbstractData & Caps;
	conditionals: AbstractData & Conditionals;
	db_queries: AbstractData & DB_Queries;
	doing_it_wrong: AbstractData & Doing_It_Wrong;
	environment: AbstractData & Environment;
	hooks: AbstractData & Hooks;
	http: AbstractData & HTTP;
	languages: AbstractData & Languages;
	logger: AbstractData & Logger;
	multisite: AbstractData & Multisite;
	overview: AbstractData & Overview;
	php_errors: AbstractData & PHP_Errors;
	raw_request: AbstractData & Raw_Request;
	redirect: AbstractData & Redirect;
	request: AbstractData & Request;
	response: AbstractData & Theme;
	timing: AbstractData & Timing;
	transients: AbstractData & Transients;
}
export interface AbstractData {
	types: {
		[k: string]: number;
	};
	concerned_filters: {
		[k: string]: ConcernedHook;
	} | null;
	concerned_actions: {
		[k: string]: ConcernedHook;
	} | null;
}
/**
 * A hook that is concerned with a particular panel.
 */
export interface ConcernedHook {
	name: string;
	type: "action" | "filter";
	actions: {
		priority: number;
		callback: Callback;
	}[];
	components: {
		[k: string]: Component;
	};
}
/**
 * Callback registered on a hook or block.
 */
export interface Callback {
	callback_type:
		| "function"
		| "method"
		| "static_method"
		| "closure"
		| "invokable"
		| "lambda"
		| "unknown"
		| "unknown_closure";
	name?: string;
	file?: string | false;
	line?: number | false;
	component?: Component;
}
/**
 * Class representing a component.
 */
export interface Component {
	type: string;
	name: string;
	context: string;
}
/**
 * Admin screen data transfer object.
 */
export interface Admin {
	current_screen?: WP_Screen;
	hook_suffix: string;
	list_table?: {
		columns_filter: string;
		sortables_filter: string;
		column_action: string;
		class_name?: string;
	};
	pagenow: string;
	taxnow: string;
	typenow: string;
}
/**
 * Asset data transfer object.
 */
export interface Assets {
	assets?: Asset[];
	url: URL;
	missing_dependencies: {
		[k: string]: true;
	};
}
export interface Asset {
	handle: string;
	position: "missing" | "broken" | "modules" | "header" | "footer";
	url: URL;
	source: string | WP_Error;
	ver: string;
	warning: boolean;
	dependents: string[];
	dependencies: string[];
	[k: string]: unknown;
}
/**
 * Parsed URL data object.
 */
export interface URL {
	host: string;
	local: boolean;
	absolute: string;
}
/**
 * Block editor data transfer object.
 */
export interface Block_Editor {
	post_blocks: PostBlock[];
	post_has_blocks: boolean;
}
export interface PostBlock {
	blockName: string | null;
	attrs: {
		[k: string]: unknown;
	};
	innerContent: (string | null)[];
	dynamic: boolean;
	callback: Callback | null;
	innerHTML: string;
	context?:
		| {
				[k: string]: unknown;
		  }[]
		| null;
	timing: number;
	innerBlocks: PostBlock[];
	[k: string]: unknown;
}
/**
 * Cache data transfer object.
 */
export interface Cache {
	has_object_cache: boolean;
	has_opcode_cache: boolean;
	cache_hit_percentage?: number;
	stats?: {
		[k: string]: boolean | number | string;
	};
	object_cache_extensions: {
		[k: string]: boolean;
	};
	opcode_cache_extensions: {
		[k: string]: boolean;
	};
}
/**
 * User capability checks data transfer object.
 */
export interface Caps {
	caps: {
		args: unknown[];
		trace: Backtrace;
		result: boolean;
		name: string;
		user: number;
	}[];
}
/**
 * Class representing a backtrace.
 */
export interface Backtrace {
	component: Component;
	callsite?: CallSite | null;
	/**
	 * Compact frame references as [frameIndex, lineNumber] tuples.
	 */
	frames: [number, number | null][];
	/**
	 * Time in milliseconds relative to the start of the request.
	 */
	time: number;
}
/**
 * Code location where an error or event occurred.
 */
export interface CallSite {
	file: string;
	line: number;
}
/**
 * Conditionals data transfer object.
 */
export interface Conditionals {
	conds: {
		true: string[];
		false: string[];
		na: string[];
	};
}
/**
 * Database queries data transfer object.
 */
export interface DB_Queries {
	total_qs: number;
	errors: number[];
	expensive?: number[];
	rows?: QueryRow[];
	has_result: boolean;
	has_trace: boolean;
	has_sqlite: boolean;
	dupes: {
		query: string;
		count: number;
		ltime: number;
		callers: {
			[k: string]: number;
		};
		components: {
			[k: string]: number;
		};
		sources: {
			[k: string]: number;
		};
	}[];
}
export interface QueryRow {
	stack?: string[];
	sql: string;
	ltime: number;
	result?: number | boolean | WP_Error;
	trace?: Backtrace;
	is_main_query?: boolean;
	sqlite_queries?: SQLiteQuery[];
}
export interface SQLiteQuery {
	sql: string;
	params?: {
		[k: string]: string | number;
	};
}
/**
 * Doing it Wrong data transfer object.
 */
export interface Doing_It_Wrong {
	actions: {
		trace: Backtrace;
		message: string;
	}[];
}
/**
 * Environment data transfer object.
 */
export interface Environment {
	php: {
		variables: {
			[k: string]: string | null;
		};
		version: string | false;
		sapi: string | false;
		user: string;
		old: boolean;
		extensions: {
			[k: string]: string;
		};
		error_reporting: number;
		error_levels: {
			[k: string]: boolean;
		};
	};
	db: {
		info: {
			"server-version": string;
			extension: string | null;
			"client-version": string | null;
			user: string;
			host: string;
			database: string;
		};
		variables: {
			Variable_name: string;
			Value: string;
		}[];
	};
	wp: {
		version: string;
		environment_type: string;
		development_mode?: string;
		constants: {
			[k: string]: string;
		};
	};
	server: {
		name: string;
		version: string | null;
		address: string | null;
		host: string | null;
		OS: string | null;
		arch: string | null;
		basicauth: "true" | "false";
	};
}
/**
 * Hooks data transfer object.
 */
export interface Hooks {
	hooks: {
		name: string;
		actions: {
			priority: number;
			callback: Callback;
		}[];
		components: {
			[k: string]: {
				[k: string]: unknown;
			};
		};
	}[];
	all_hooks: boolean;
	php_int_max: number;
	php_int_min: number;
}
/**
 * HTTP data transfer object.
 */
export interface HTTP {
	http: {
		args: {
			method: string;
			timeout: number;
			redirection?: number;
			blocking?: boolean;
			sslverify?: boolean;
			[k: string]: unknown;
		};
		trace: Backtrace;
		info: {
			[k: string]: unknown;
		} | null;
		host: string;
		local: boolean;
		ltime: number;
		redirected_to: string | null;
		result:
			| {
					code: number;
					message: string;
			  }
			| WP_Error;
		type: string;
		url: string;
		intercepted: boolean;
	}[];
	ltime: number;
	errors: {
		alert?: string[];
		warning?: string[];
	};
}
/**
 * Languages data transfer object.
 */
export interface Languages {
	languages: {
		caller: StackFrame | false;
		domain: string;
		file: string | false;
		found: number | false;
		handle: string | null;
		type: "gettext" | "jed" | "php" | "unknown";
	}[];
	locale: string;
	user_locale: string;
	determined_locale: string;
	language_attributes: string;
	/**
	 * MultilingualPress language.
	 */
	mlp_language: string;
	/**
	 * Polylang language.
	 */
	pll_language: string;
}
/**
 * Stack trace frame.
 */
export interface StackFrame {
	id: string;
	args?: string | null;
	file: string | null;
	line?: number | null;
}
/**
 * Logger data transfer object.
 */
export interface Logger {
	logs: {
		message: string;
		trace: Backtrace;
		level: string;
		context: {
			[k: string]: unknown;
		};
	}[];
}
/**
 * Multisite data transfer object.
 */
export interface Multisite {
	switches: {
		new: number;
		prev: number;
		to: boolean;
		trace: Backtrace;
	}[];
}
/**
 * Overview data transfer object.
 */
export interface Overview {
	time_taken?: number;
	time_limit: number;
	time_usage: number;
	memory: number;
	memory_limit: number;
	memory_usage: number;
	actions?: {
		[k: string]: {
			start: number;
			end?: number;
		}[];
	};
	segments?: {
		init: number;
		request?: number;
		query?: number;
		template?: number;
		shutdown?: number;
	};
}
/**
 * PHP errors data transfer object.
 */
export interface PHP_Errors {
	errors: {
		[k: string]: PHP_Error;
	};
}
/**
 * Individual PHP error data object.
 */
export interface PHP_Error {
	errno: number;
	level: "warning" | "notice" | "strict" | "deprecated";
	suppressed: boolean;
	message: string;
	trace?: Backtrace | null;
	count: number;
}
/**
 * Raw request data transfer object.
 */
export interface Raw_Request {
	request: {
		[k: string]: unknown;
	};
	response: {
		[k: string]: unknown;
	};
}
/**
 * Redirect data transfer object.
 */
export interface Redirect {
	trace?: Backtrace;
	location?: string;
	status?: number;
}
/**
 * Request data transfer object.
 */
export interface Request {
	user: {
		title: string;
		id: number | false;
	};
	multisite: {
		current_site?: {
			title: string;
			data: WP_Site;
		};
		current_network?: {
			title: string;
			data: WP_Network;
		};
	};
	request: {
		request: string;
		matched_rule?: string;
		matched_query?: string;
		query_string: string;
	};
	qvars: {
		[k: string]:
			| string
			| unknown[]
			| {
					[k: string]: unknown;
			  };
	};
	queried_object?: {
		title: string;
		data?: WP_Term | WP_Post_Type | WP_Post | WP_User;
		type?: "WP_Term" | "WP_Post_Type" | "WP_Post" | "WP_User";
	};
	matching_rewrites: {
		[k: string]: string;
	};
}
/**
 * Theme data transfer object.
 */
export interface Theme {
	is_child_theme: boolean;
	stylesheet_theme_json: string;
	template_theme_json: string;
	block_template: WP_Block_Template | null;
	theme_dirs: {
		[k: string]: string;
	};
	theme_folders: {
		[k: string]: string;
	};
	stylesheet: string;
	template: string;
	theme_template_file: string;
	template_path: string;
	template_file?: string;
	template_hierarchy?: string[];
	timber_files?: string[];
	body_class?: string[];
	template_parts: {
		[k: string]: string;
	};
	theme_template_parts: {
		[k: string]: string;
	};
	count_template_parts: {
		[k: string]: number;
	};
	unsuccessful_template_parts: {
		slug: string;
		name: string | null;
		caller: {
			file: string;
			line: number;
		};
	}[];
}
/**
 * Timing data transfer object.
 */
export interface Timing {
	warning: {
		function: string;
		message: string;
		trace: Backtrace;
	}[];
	timing: {
		function: string;
		function_time: number;
		function_memory: number;
		laps: {
			[k: string]: {
				time: number;
				time_used: number;
				memory: number;
				memory_used: number;
				data: unknown;
			};
		};
		trace: Backtrace;
		start_time: number;
		end_time: number;
	}[];
}
/**
 * Transients data transfer object.
 */
export interface Transients {
	trans: {
		name: string;
		trace: Backtrace;
		type: "blog" | "site";
		expiration: number;
		exp_diff: string;
		size: number;
	}[];
	has_type: boolean;
}
