<?php declare(strict_types = 1);
/**
 * This file is generated by the generate.mjs script.
 * Do not edit it manually.
 */

/**
 * QM_Data_Post_Block data object.
 *
 * @package query-monitor
 */

class QM_Data_Post_Block {
	/**
	 * @var string|null
	 */
	public $blockName;

	/**
	 * @var array<string, mixed>
	 */
	public $attrs;

	/**
	 * @var array<int, string|null>
	 */
	public $innerContent;

	/**
	 * @var bool
	 */
	public $dynamic;

	/**
	 * @var ?QM_Data_Callback
	 */
	public $callback;

	/**
	 * @var string
	 */
	public $innerHTML;

	/**
	 * @var ?array|null
	 */
	public $context;

	/**
	 * @var float
	 */
	public $timing;

	/**
	 * @var array<int, QM_Data_Post_Block>
	 */
	public $innerBlocks;
}
