<?php declare(strict_types = 1);
/**
 * This file is generated by the generate.mjs script.
 * Do not edit it manually.
 */

/**
 * QM_Data_HTTP_Response data object.
 *
 * @package query-monitor
 */

class QM_Data_HTTP_Response {
	/**
	 * @var int
	 */
	public $code;

	/**
	 * @var string
	 */
	public $message;
}
