<?php declare(strict_types = 1);
/**
 * This file is generated by the generate.mjs script.
 * Do not edit it manually.
 */

/**
 * QM_Data_HTTP_Request data object.
 *
 * @package query-monitor
 */

class QM_Data_HTTP_Request {
	/**
	 * @phpstan-var array{
	 *   method: string,
	 *   timeout: float,
	 *   redirection?: int,
	 *   blocking?: bool,
	 *   sslverify?: bool,
	 * }
	 */
	public $args;

	/**
	 * @var QM_Backtrace
	 */
	public $trace;

	/**
	 * @var array<string, mixed>|null
	 */
	public $info;

	/**
	 * @var string
	 */
	public $host;

	/**
	 * @var bool
	 */
	public $local;

	/**
	 * @var float
	 */
	public $ltime;

	/**
	 * @var string|null
	 */
	public $redirected_to;

	/**
	 * @var QM_Data_HTTP_Response|WP_Error
	 */
	public $result;

	/**
	 * @var string
	 */
	public $type;

	/**
	 * @var string
	 */
	public $url;

	/**
	 * @var bool
	 */
	public $intercepted;
}
