<?php declare(strict_types = 1);
/**
 * This file is generated by the generate.mjs script.
 * Do not edit it manually.
 *
 * Source schema: src/schemas/data/assets.json
 */

/**
 * Asset data transfer object.
 *
 * @package query-monitor
 */

/**
 * @phpstan-type Asset array{
 *   host: string,
 *   port: string,
 *   source: string|WP_Error,
 *   local: bool,
 *   ver: string,
 *   warning: bool,
 *   display: string,
 *   dependents: array<string>,
 *   dependencies: array<string>,
 * }
 * @phpstan-type AssetList array<string, Asset>
 */
class QM_Data_Assets extends QM_Data {
	/**
	 * @phpstan-var ?array{
	 *   missing: AssetList,
	 *   broken: AssetList,
	 *   header: AssetList,
	 *   footer: AssetList,
	 * }
	 */
	public $assets;

	/**
	 * @phpstan-var array{
	 *   missing: int,
	 *   broken: int,
	 *   header: int,
	 *   footer: int,
	 *   total: int,
	 * }
	 */
	public $counts;

	/**
	 * @var string
	 */
	public $default_version;

	/**
	 * @var array<int, string>
	 */
	public $dependencies;

	/**
	 * @var array<int, string>
	 */
	public $dependents;

	/**
	 * @var array<int, string>
	 */
	public $footer;

	/**
	 * @var array<int, string>
	 */
	public $header;

	/**
	 * @var string
	 */
	public $full_host;

	/**
	 * @var string
	 */
	public $host;

	/**
	 * @var bool
	 */
	public $is_ssl;

	/**
	 * @var array<string, true>
	 */
	public $missing_dependencies;

	/**
	 * @var string
	 */
	public $port;
}
