<?php declare(strict_types = 1);
/**
 * This file is generated by the generate.mjs script.
 * Do not edit it manually.
 *
 * Source schema: src/schemas/data/assets.json
 */

/**
 * Asset data transfer object.
 *
 * @package query-monitor
 */

/**
 * @phpstan-type Asset array{
 *   handle: string,
 *   position: 'missing'|'broken'|'header'|'footer',
 *   host: string,
 *   port: string,
 *   source: string|WP_Error,
 *   local: bool,
 *   ver: string,
 *   warning: bool,
 *   display: string,
 *   dependents: array<int, string>,
 *   dependencies: array<int, string>,
 * }
 */
class QM_Data_Assets extends QM_Data {
	/**
	 * @var ?array<int, Asset>
	 */
	public $assets;

	/**
	 * @var string
	 */
	public $default_version;

	/**
	 * @var string
	 */
	public $full_host;

	/**
	 * @var string
	 */
	public $host;

	/**
	 * @var bool
	 */
	public $is_ssl;

	/**
	 * @var array<string, true>
	 */
	public $missing_dependencies;

	/**
	 * @var string
	 */
	public $port;
}
