<?php declare(strict_types = 1);
/**
 * This file is generated by the generate.mjs script.
 * Do not edit it manually.
 *
 * Source schema: src/schemas/data/assets.json
 */

/**
 * Asset data transfer object.
 *
 * @package query-monitor
 */

/**
 * @phpstan-type Asset array{
 *   handle: string,
 *   position: 'missing'|'broken'|'modules'|'header'|'footer',
 *   url: mixed,
 *   source: string|WP_Error,
 *   ver: string,
 *   warning: bool,
 *   dependents: array<int, string>,
 *   dependencies: array<int, string>,
 * }
 */
class QM_Data_Assets extends QM_Data {
	/**
	 * @var ?array<int, Asset>
	 */
	public $assets;

	/**
	 * @var mixed
	 */
	public $url;

	/**
	 * @var array<string, true>
	 */
	public $missing_dependencies;
}
