<?php declare(strict_types = 1);
/**
 * This file is generated by the generate.mjs script.
 * Do not edit it manually.
 *
 * Source schema: src/schemas/data/block_editor.json
 */

/**
 * Block editor data transfer object.
 *
 * @package query-monitor
 */

class QM_Data_Block_Editor extends QM_Data {
	/**
	 * @var array<int, QM_Data_Post_Block>
	 */
	public $post_blocks;

	/**
	 * @var bool
	 */
	public $post_has_blocks;
}
