<?php declare(strict_types = 1);
/**
 * This file is generated by the generate.mjs script.
 * Do not edit it manually.
 */

/**
 * QM_Data_CallSite data object.
 *
 * Code location where an error or event occurred.
 *
 * @package query-monitor
 */

class QM_Data_CallSite {
	/**
	 * @var string|null
	 */
	public $file;

	/**
	 * @var string
	 */
	public $filename;

	/**
	 * @var int|null
	 */
	public $line;
}
