<?php declare(strict_types = 1);
/**
 * This file is generated by the generate.mjs script.
 * Do not edit it manually.
 */

/**
 * Callback registered on a hook or block.
 *
 * @package query-monitor
 */

class QM_Data_Callback {
	/**
	 * @var ?int
	 */
	public $accepted_args;

	/**
	 * @var 'function'|'method'|'static_method'|'closure'|'invokable'|'lambda'|'unknown'|'unknown_closure'
	 */
	public $callback_type;

	/**
	 * @var ?string
	 */
	public $name;

	/**
	 * @var ?string|false
	 */
	public $file;

	/**
	 * @var ?int|false
	 */
	public $line;

	/**
	 * @var ?int
	 */
	public $start_line;

	/**
	 * @var ?string
	 */
	public $display_file;

	/**
	 * @var ?WP_Error
	 */
	public $error;

	/**
	 * @var ?QM_Component
	 */
	public $component;
}
