<?php declare(strict_types = 1);
/**
 * This file is generated by the generate.mjs script.
 * Do not edit it manually.
 */

/**
 * Code location where an error or event occurred.
 *
 * @package query-monitor
 */

class QM_Data_Callsite {
	/**
	 * @var string
	 */
	public $file;

	/**
	 * @var int
	 */
	public $line;
}
