<?php declare(strict_types = 1);
/**
 * This file is generated by the generate.mjs script.
 * Do not edit it manually.
 */

/**
 * Callback registered on a hook or block.
 *
 * @package query-monitor
 */

/**
 * @implements \ArrayAccess<string,mixed>
 */
class QM_Data_Callback implements \ArrayAccess {
	use QM_ArrayAccess;

	/**
	 * @var 'function'|'method'|'static_method'|'closure'|'invokable'|'lambda'|'unknown'|'unknown_closure'
	 */
	public $callback_type;

	/**
	 * @var ?string
	 */
	public $name;

	/**
	 * @var ?string|false
	 */
	public $file;

	/**
	 * @var ?int|false
	 */
	public $line;

	/**
	 * @var ?QM_Component
	 */
	public $component;
}
