<?php declare(strict_types = 1);
/**
 * This file is generated by the generate.mjs script.
 * Do not edit it manually.
 *
 * Source schema: src/schemas/data/caps.json
 */

/**
 * User capability checks data transfer object.
 *
 * @package query-monitor
 */

class QM_Data_Caps extends QM_Data {
	/**
	 * @phpstan-var array<int, array{
	 *   args: array<int, mixed>,
	 *   trace: QM_Backtrace,
	 *   result: bool,
	 *   name: string,
	 *   user: string,
	 * }>
	 */
	public $caps;
}
