<?php declare(strict_types = 1);
/**
 * This file is generated by the generate.mjs script.
 * Do not edit it manually.
 *
 * Source schema: src/schemas/data/conditionals.json
 */

/**
 * Conditionals data transfer object.
 *
 * @package query-monitor
 */

class QM_Data_Conditionals extends QM_Data {
	/**
	 * @phpstan-var array{
	 *   true: array<int, string>,
	 *   false: array<int, string>,
	 *   na: array<int, string>,
	 * }
	 */
	public $conds;
}
