<?php declare(strict_types = 1);
/**
 * This file is generated by the generate.mjs script.
 * Do not edit it manually.
 *
 * Source schema: src/schemas/data/db_components.json
 */

/**
 * Database query components data transfer object.
 *
 * @package query-monitor
 */

class QM_Data_DB_Components extends QM_Data {
	/**
	 * @phpstan-var array<string, array{
	 *   ltime: float,
	 *   types: array<string, int>,
	 *   component: string,
	 * }>
	 */
	public $times;
}
