<?php declare(strict_types = 1);
/**
 * This file is generated by the generate.mjs script.
 * Do not edit it manually.
 *
 * Source schema: src/schemas/data/db_callers.json
 */

/**
 * Database query callers data transfer object.
 *
 * @package query-monitor
 */

class QM_Data_DB_Callers extends QM_Data {
	/**
	 * @phpstan-var array<string, array{
	 *   caller: string,
	 *   ltime: float,
	 *   types: array<string, int>,
	 * }>
	 */
	public $times;
}
