<?php declare(strict_types = 1);
/**
 * This file is generated by the generate.mjs script.
 * Do not edit it manually.
 */

/**
 * Database queries data transfer object.
 *
 * @package query-monitor
 */

class QM_Data_DB_Queries extends QM_Data {
	/**
	 * @var int
	 */
	public $total_qs;

	/**
	 * @var float
	 */
	public $total_time;

	/**
	 * @var array<int, array<string, mixed>>
	 */
	public $errors;

	/**
	 * @var ?array<int, array<string, mixed>>
	 */
	public $expensive;

	/**
	 * @phpstan-var ?object{
	 *   rows: array<int, array{
	 *     caller: array|null,
	 *     caller_name: string|null,
	 *     stack: array<string, mixed>,
	 *     sql: string,
	 *     ltime: float,
	 *     result: int|bool|WP_Error,
	 *     type: string,
	 *     component: QM_Component|null,
	 *     trace: array<string, mixed>,
	 *     is_main_query: bool,
	 *     filtered_trace?: array<int, array<string, mixed>>,
	 *   }>,
	 *   types: array<string, mixed>,
	 *   has_result: bool,
	 *   has_trace: bool,
	 *   has_main_query: bool,
	 * }
	 */
	public $rows;

	/**
	 * @var bool
	 */
	public $has_result;

	/**
	 * @var bool
	 */
	public $has_trace;

	/**
	 * @var bool
	 */
	public $has_main_query;

	/**
	 * @phpstan-var ?array<string, array{
	 *   caller: string,
	 *   ltime: float,
	 *   types: array<string, int>,
	 * }>
	 */
	public $times;

	/**
	 * @var ?array<string, array<int, int>>
	 */
	public $dupes;
}
