<?php declare(strict_types = 1);
/**
 * This file is generated by the generate.mjs script.
 * Do not edit it manually.
 *
 * Source schema: src/schemas/data/db_queries.json
 */

/**
 * Database queries data transfer object.
 *
 * @package query-monitor
 */

/**
 * @phpstan-type QueryRow array{
 *   stack?: array<int, string>,
 *   sql: string,
 *   ltime: float,
 *   result?: int|bool|WP_Error,
 *   type: string,
 *   trace?: QM_Backtrace,
 *   is_main_query: bool,
 * }
 */
class QM_Data_DB_Queries extends QM_Data {
	/**
	 * @var int
	 */
	public $total_qs;

	/**
	 * @var float
	 */
	public $total_time;

	/**
	 * @var array<int, int>
	 */
	public $errors;

	/**
	 * @var ?array<int, int>
	 */
	public $expensive;

	/**
	 * @phpstan-var ?array<int, QueryRow>
	 */
	public $rows;

	/**
	 * @var bool
	 */
	public $has_result;

	/**
	 * @var bool
	 */
	public $has_trace;

	/**
	 * @var bool
	 */
	public $has_main_query;

	/**
	 * @phpstan-var ?array<string, array{
	 *   caller: string,
	 *   ltime: float,
	 *   types: array<string, int>,
	 * }>
	 */
	public $times;

	/**
	 * @phpstan-var array<int, array{
	 *   query: string,
	 *   count: int,
	 *   ltime: float,
	 *   callers: array<string, int>,
	 *   components: array<string, int>,
	 *   sources: array<string, int>,
	 * }>
	 */
	public $dupes;
}
