<?php declare(strict_types = 1);
/**
 * This file is generated by the generate.mjs script.
 * Do not edit it manually.
 *
 * Source schema: src/schemas/data/doing_it_wrong.json
 */

/**
 * Doing it Wrong data transfer object.
 *
 * @package query-monitor
 */

class QM_Data_Doing_It_Wrong extends QM_Data {
	/**
	 * @phpstan-var array<int, array{
	 *   hook: string,
	 *   trace: QM_Backtrace,
	 *   message: string,
	 * }>
	 */
	public $actions;
}
