<?php declare(strict_types = 1);
/**
 * This file is generated by the generate.mjs script.
 * Do not edit it manually.
 */

/**
 * Doing it Wrong data transfer object.
 *
 * @package query-monitor
 */

class QM_Data_Doing_It_Wrong extends QM_Data {
	/**
	 * @phpstan-var array<int, array{
	 *   hook: string,
	 *   filtered_trace: array<int, array<string, mixed>>,
	 *   message: string,
	 *   component: QM_Component,
	 * }>
	 */
	public $actions;
}
