<?php declare(strict_types = 1);
/**
 * This file is generated by the generate.mjs script.
 * Do not edit it manually.
 */

/**
 * Environment data transfer object.
 *
 * @package query-monitor
 */

class QM_Data_Environment extends QM_Data {
	/**
	 * @phpstan-var array{
	 *   variables: array<string, string|null>,
	 *   version: string|false,
	 *   sapi: string|false,
	 *   user: string,
	 *   old: bool,
	 *   extensions: array<string, string>,
	 *   error_reporting: int,
	 *   error_levels: array<string, bool>,
	 * }
	 */
	public $php;

	/**
	 * @phpstan-var array{
	 *   info: array{
	 *     server-version: string,
	 *     extension: string|null,
	 *     client-version: string|null,
	 *     user: string,
	 *     host: string,
	 *     database: string,
	 *   },
	 *   variables: array<int, stdClass>,
	 * }
	 */
	public $db;

	/**
	 * @phpstan-var array{
	 *   version: string,
	 *   environment_type?: string,
	 *   development_mode?: string,
	 *   constants: array<string, string>,
	 * }
	 */
	public $wp;

	/**
	 * @phpstan-var array{
	 *   name: string,
	 *   version: string|null,
	 *   address: string|null,
	 *   host: string|null,
	 *   OS: string|null,
	 *   arch: string|null,
	 * }
	 */
	public $server;
}
