<?php declare(strict_types = 1);
/**
 * This file is generated by the generate.mjs script.
 * Do not edit it manually.
 */

/**
 * Stack trace frame.
 *
 * @package query-monitor
 */

/**
 * @implements \ArrayAccess<string,mixed>
 */
class QM_Data_Stack_Frame implements \ArrayAccess {
	use QM_ArrayAccess;

	/**
	 * @var string
	 */
	public $id;

	/**
	 * @var ?string|null
	 */
	public $args;

	/**
	 * @var string|null
	 */
	public $file;

	/**
	 * @var ?int|null
	 */
	public $line;
}
