<?php declare(strict_types = 1);
/**
 * This file is generated by the generate.mjs script.
 * Do not edit it manually.
 *
 * Source schema: src/schemas/data/hooks.json
 */

/**
 * Hooks data transfer object.
 *
 * @package query-monitor
 */

class QM_Data_Hooks extends QM_Data {
	/**
	 * @phpstan-var array<int, array{
	 *   name: string,
	 *   actions: array<int, array{
	 *     priority: int,
	 *     callback: QM_Data_Callback,
	 *   }>,
	 *   components: array<string, QM_Component>,
	 * }>
	 */
	public $hooks;

	/**
	 * @var bool
	 */
	public $all_hooks;

	/**
	 * @var int
	 */
	public $php_int_max;

	/**
	 * @var int
	 */
	public $php_int_min;
}
