<?php declare(strict_types = 1);
/**
 * This file is generated by the generate.mjs script.
 * Do not edit it manually.
 *
 * Source schema: src/schemas/data/hooks.json
 */

/**
 * Hooks data transfer object.
 *
 * @package query-monitor
 */

class QM_Data_Hooks extends QM_Data {
	/**
	 * @phpstan-var array<int, array{
	 *   name: string,
	 *   actions: array<int, array{
	 *     priority: int,
	 *     callback: array{
	 *       accepted_args: int,
	 *       name?: string,
	 *       callback_type?: string,
	 *       display_file?: string,
	 *       file?: string|false,
	 *       line?: int|false,
	 *       error?: WP_Error,
	 *       component?: QM_Component,
	 *     },
	 *   }>,
	 *   components: array<string, QM_Component>,
	 * }>
	 */
	public $hooks;

	/**
	 * @phpstan-var array<int, array<string, QM_Component>>
	 */
	public $components;

	/**
	 * @var bool
	 */
	public $all_hooks;
}
