<?php declare(strict_types = 1);
/**
 * This file is generated by the generate.mjs script.
 * Do not edit it manually.
 *
 * Source schema: src/schemas/data/http.json
 */

/**
 * HTTP data transfer object.
 *
 * @package query-monitor
 */

class QM_Data_HTTP extends QM_Data {
	/**
	 * @var array<int, QM_Data_HTTP_Request>
	 */
	public $http;

	/**
	 * @var float
	 */
	public $ltime;

	/**
	 * @phpstan-var array{
	 *   alert?: array<int, string>,
	 *   warning?: array<int, string>,
	 * }
	 */
	public $errors;
}
