<?php declare(strict_types = 1);
/**
 * This file is generated by the generate.mjs script.
 * Do not edit it manually.
 *
 * Source schema: src/schemas/data/http.json
 */

/**
 * HTTP data transfer object.
 *
 * @package query-monitor
 */

class QM_Data_HTTP extends QM_Data {
	/**
	 * @phpstan-var array<string, array{
	 *   args: array{
	 *     method: string,
	 *     timeout: float,
	 *     redirection?: int,
	 *     blocking?: bool,
	 *     sslverify?: bool,
	 *   },
	 *   trace: QM_Backtrace,
	 *   info: array<string, mixed>|null,
	 *   host: string,
	 *   local: bool,
	 *   ltime: float,
	 *   redirected_to: string|null,
	 *   response: array{
	 *     headers: array<string, mixed>,
	 *     body: string,
	 *     response: array{
	 *       code: int,
	 *       message: string,
	 *     },
	 *     cookies: array<int, WP_HTTP_Cookie>,
	 *     filename: string|null,
	 *     http_response: WP_HTTP_Requests_Response,
	 *   }|WP_Error,
	 *   type: string,
	 *   url: string,
	 * }>
	 */
	public $http;

	/**
	 * @var float
	 */
	public $ltime;

	/**
	 * @phpstan-var array{
	 *   alert?: array<int, string>,
	 *   warning?: array<int, string>,
	 * }
	 */
	public $errors;
}
