<?php declare(strict_types = 1);
/**
 * This file is generated by the generate.mjs script.
 * Do not edit it manually.
 */

/**
 * HTTP data transfer object.
 *
 * @package query-monitor
 */

class QM_Data_HTTP extends QM_Data {
	/**
	 * @phpstan-var array<string, array{
	 *   args: array<string, mixed>,
	 *   component: QM_Component,
	 *   filtered_trace: array<int, array<string, mixed>>,
	 *   info: array<string, mixed>|null,
	 *   local: bool,
	 *   ltime: float,
	 *   redirected_to: string|null,
	 *   response: array<string, mixed>|WP_Error,
	 *   type: string,
	 *   url: string,
	 * }>
	 */
	public $http;

	/**
	 * @var float
	 */
	public $ltime;

	/**
	 * @phpstan-var array{
	 *   alert?: array<int, string>,
	 *   warning?: array<int, string>,
	 * }
	 */
	public $errors;
}
