<?php declare(strict_types = 1);
/**
 * This file is generated by the generate.mjs script.
 * Do not edit it manually.
 *
 * Source schema: src/schemas/data/languages.json
 */

/**
 * Languages data transfer object.
 *
 * @package query-monitor
 */

class QM_Data_Languages extends QM_Data {
	/**
	 * @phpstan-var array<int, array{
	 *   caller: array<string, mixed>|false,
	 *   domain: string,
	 *   file: string|false,
	 *   found: int|false,
	 *   handle: string|null,
	 *   type: 'gettext'|'jed'|'php'|'unknown',
	 * }>
	 */
	public $languages;

	/**
	 * @var string
	 */
	public $locale;

	/**
	 * @var string
	 */
	public $user_locale;

	/**
	 * @var string
	 */
	public $determined_locale;

	/**
	 * @var string
	 */
	public $language_attributes;

	/**
	 * MultilingualPress language.
	 *
	 * @var string
	 */
	public $mlp_language;

	/**
	 * Polylang language.
	 *
	 * @var string
	 */
	public $pll_language;
}
