<?php declare(strict_types = 1);
/**
 * This file is generated by the generate.mjs script.
 * Do not edit it manually.
 */

/**
 * Logger data transfer object.
 *
 * @package query-monitor
 */

class QM_Data_Logger extends QM_Data {
	/**
	 * @phpstan-var array<QM_Collector_Logger::*, int>
	 */
	public $counts;

	/**
	 * @phpstan-var array<int, array{
	 *   message: string,
	 *   filtered_trace: array<int, array<string, mixed>>,
	 *   component: QM_Component,
	 *   level: QM_Collector_Logger::*,
	 * }>
	 */
	public $logs;

	/**
	 * @var array<string, string>
	 */
	public $components;

	/**
	 * @var array<int, string>
	 */
	public $levels;

	/**
	 * @var array<int, string>
	 */
	public $warning_levels;
}
