<?php declare(strict_types = 1);
/**
 * This file is generated by the generate.mjs script.
 * Do not edit it manually.
 *
 * Source schema: src/schemas/data/multisite.json
 */

/**
 * Multisite data transfer object.
 *
 * @package query-monitor
 */

class QM_Data_Multisite extends QM_Data {
	/**
	 * @phpstan-var array<int, array{
	 *   new: int,
	 *   prev: int,
	 *   to: bool,
	 *   trace: QM_Backtrace,
	 * }>
	 */
	public $switches;
}
