<?php declare(strict_types = 1);
/**
 * This file is generated by the generate.mjs script.
 * Do not edit it manually.
 *
 * Source schema: src/schemas/data/overview.json
 */

/**
 * Overview data transfer object.
 *
 * @package query-monitor
 */

class QM_Data_Overview extends QM_Data {
	/**
	 * @var ?float
	 */
	public $time_taken;

	/**
	 * @var int
	 */
	public $time_limit;

	/**
	 * @var int|float
	 */
	public $time_usage;

	/**
	 * @var int
	 */
	public $memory;

	/**
	 * @var float
	 */
	public $memory_limit;

	/**
	 * @var int|float
	 */
	public $memory_usage;

	/**
	 * @phpstan-var ?array<string, array<int, array{
	 *   start: float,
	 *   end?: float,
	 * }>>
	 */
	public $actions;

	/**
	 * @phpstan-var ?array{
	 *   init: float,
	 *   request?: float,
	 *   query?: float,
	 *   template?: float,
	 *   shutdown?: float,
	 * }
	 */
	public $segments;
}
