<?php declare(strict_types = 1);
/**
 * This file is generated by the generate.mjs script.
 * Do not edit it manually.
 */

/**
 * Individual PHP error data object.
 *
 * @package query-monitor
 */

/**
 * @implements \ArrayAccess<string,mixed>
 */
class QM_Data_PHP_Error implements \ArrayAccess {
	use QM_ArrayAccess;

	/**
	 * @var int
	 */
	public $errno;

	/**
	 * @var 'warning'|'notice'|'strict'|'deprecated'
	 */
	public $level;

	/**
	 * @var bool
	 */
	public $suppressed;

	/**
	 * @var string
	 */
	public $message;

	/**
	 * @var ?QM_Backtrace
	 */
	public $trace;

	/**
	 * @var int
	 */
	public $count;
}
