<?php declare(strict_types = 1);
/**
 * This file is generated by the generate.mjs script.
 * Do not edit it manually.
 */

/**
 * PHP errors data transfer object.
 *
 * @package query-monitor
 */

/**
 * @phpstan-type errorObject array{
 *   errno: int,
 *   type: string,
 *   message: string,
 *   file: string|null,
 *   filename: string,
 *   line: int|null,
 *   filtered_trace: list<array<string, mixed>>|null,
 *   component: QM_Component,
 *   calls: int,
 * }
 * @phpstan-type errorObjects array<string, array<string, errorObject>>
 */
class QM_Data_PHP_Errors extends QM_Data {
	/**
	 * @var array<string, string>
	 */
	public $components;

	/**
	 * @phpstan-var errorObjects
	 */
	public $errors;

	/**
	 * @phpstan-var errorObjects
	 */
	public $suppressed;

	/**
	 * @phpstan-var errorObjects
	 */
	public $silenced;
}
