<?php declare(strict_types = 1);
/**
 * This file is generated by the generate.mjs script.
 * Do not edit it manually.
 *
 * Source schema: src/schemas/data/php_errors.json
 */

/**
 * PHP errors data transfer object.
 *
 * @package query-monitor
 */

class QM_Data_PHP_Errors extends QM_Data {
	/**
	 * @var array<string, QM_Data_PHP_Error>
	 */
	public $errors;
}
