<?php declare(strict_types = 1);
/**
 * This file is generated by the generate.mjs script.
 * Do not edit it manually.
 *
 * Source schema: src/schemas/data/raw_request.json
 */

/**
 * Raw request data transfer object.
 *
 * @package query-monitor
 */

class QM_Data_Raw_Request extends QM_Data {
	/**
	 * @var QM_Data_Raw_Request_Request
	 */
	public $request;

	/**
	 * @var QM_Data_Raw_Request_Response
	 */
	public $response;
}
