<?php declare(strict_types = 1);
/**
 * This file is generated by the generate.mjs script.
 * Do not edit it manually.
 */

/**
 * Raw request data transfer object.
 *
 * @package query-monitor
 */

class QM_Data_Raw_Request extends QM_Data {
	/**
	 * @var array<string, mixed>
	 */
	public $request;

	/**
	 * @var array<string, mixed>
	 */
	public $response;
}
