<?php declare(strict_types = 1);
/**
 * This file is generated by the generate.mjs script.
 * Do not edit it manually.
 *
 * Source schema: src/schemas/data/timing.json
 */

/**
 * Timing data transfer object.
 *
 * @package query-monitor
 */

class QM_Data_Timing extends QM_Data {
	/**
	 * @phpstan-var array<int, array{
	 *   function: string,
	 *   message: string,
	 *   filtered_trace: array<int, array<string, mixed>>,
	 *   component: QM_Component,
	 * }>
	 */
	public $warning;

	/**
	 * @phpstan-var array<int, array{
	 *   function: string,
	 *   function_time: float,
	 *   function_memory: int,
	 *   laps: array<string, array{
	 *     time: float,
	 *     time_used: float,
	 *     memory: int,
	 *     memory_used: int,
	 *     data: mixed,
	 *   }>,
	 *   filtered_trace: array<int, array<string, mixed>>,
	 *   component: QM_Component,
	 *   start_time: float,
	 *   end_time: float,
	 * }>
	 */
	public $timing;
}
