<?php declare(strict_types = 1);
/**
 * This file is generated by the generate.mjs script.
 * Do not edit it manually.
 *
 * Source schema: src/schemas/data/transients.json
 */

/**
 * Transients data transfer object.
 *
 * @package query-monitor
 */

class QM_Data_Transients extends QM_Data {
	/**
	 * @phpstan-var array<int, array{
	 *   name: string,
	 *   filtered_trace: array<int, array<string, mixed>>,
	 *   component: QM_Component,
	 *   type: string,
	 *   value: mixed,
	 *   expiration: int,
	 *   exp_diff: string,
	 *   size: int,
	 *   size_formatted: string,
	 * }>
	 */
	public $trans;

	/**
	 * @var bool
	 */
	public $has_type;
}
