<?php declare(strict_types = 1);
/**
 * This file is generated by the generate.mjs script.
 * Do not edit it manually.
 */

/**
 * Parsed URL data object.
 *
 * @package query-monitor
 */

class QM_Data_URL {
	/**
	 * @var string
	 */
	public $origin;

	/**
	 * @var string
	 */
	public $scheme;

	/**
	 * @var string
	 */
	public $hostname;

	/**
	 * @var string
	 */
	public $host;

	/**
	 * @var bool
	 */
	public $insecure;

	/**
	 * @var bool
	 */
	public $local;

	/**
	 * @var string
	 */
	public $absolute;
}
