# Configuration for Jekyll, which is used to build the documentation site from the `/docs` directory.

title: Query Monitor
description: Query Monitor is the developer tools panel for WordPress
permalink: pretty

remote_theme: just-the-docs/just-the-docs@v0.7.0
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/johnbillion/query-monitor"
gh_edit_branch: "develop"

aux_links:
  "Download":
    - "https://wordpress.org/plugins/query-monitor/"

plugins:
  - jekyll-redirect-from
