import fs from 'fs';

const dir = './src/schemas/data';
const files = fs.readdirSync( dir );

for ( const file of files ) {
	const [ basename, ext ] = file.split( '.' );

	if ( ext !== 'json' ) {
		continue;
	}

	const path = `${dir}/${file}`;
	const schema = JSON.parse( fs.readFileSync( path, 'utf8' ) );
	const output = getOutput( schema );

	fs.writeFileSync( `./data/${basename}.php`, output );
}

/**
 * @param {object} schema
 * @returns {string}
 */
function getOutput( schema ) {
	let output = `<?php declare(strict_types = 1);
/**
 * This file is generated by the generate.mjs script.
 * Do not edit it manually.
 */

/**
 * ${schema.description}
 *
 * @package query-monitor
 */
${schema.$comment ? `\n${schema.$comment}` : ''}
class QM_Data_${schema.title} extends QM_Data {`;

	for ( const key in schema.properties ) {
		const required = schema.required && schema.required.includes( key );
		const prop = resolveRef( schema.properties[key], schema );

		output += `
	/**`;

		const type = mapType( prop, required, schema );

		if ( type.includes( 'array{' ) || prop.phpStanType ) {
			output += `
	 * @phpstan-var ${type}`;
		} else {
			output += `
	 * @var ${type}`;
		}

		output += `
	 */
	public $${key};
`;
	}

	output += `}
`;

	return output;
}

/**
 * @param {object} prop
 * @param {boolean} required
 * @param {object} schema
 * @param {number} level
 * @returns {string}
 */
function mapType( prop, required, schema, level = 0 ) {
	prop = resolveRef( prop, schema );

	const type = prop.enum || prop.type;
	const requiredMarker = required ? '' : '?';
	let returnType = type;

	if ( prop.phpStanType || prop.phpType ) {
		return `${requiredMarker}${prop.phpStanType || prop.phpType}`;
	}

	if ( prop.anyOf ) {
		return `${requiredMarker}${ prop.anyOf.map( ( one ) => mapType( one, true, schema, level ) ).join( '|' ) }`;
	}

	if ( prop.oneOf ) {
		return `${requiredMarker}${ prop.oneOf.map( ( one ) => mapType( one, true, schema, level ) ).join( '|' ) }`;
	}

	if ( typeof type === 'undefined' ) {
		return `${requiredMarker}mixed`;
	}

	if ( typeof type == 'object' ) {
		return `${requiredMarker}${ type.map( getPHPType ).join( '|' ) }`;
	}

	const indentation = '  '.repeat( level );

	switch ( type ) {
		case 'array':
			if ( prop.items ) {
				returnType = `array<int, ${mapType( prop.items, true, schema, level )}>`;
			} else {
				returnType = 'array<int, mixed>';
			}
			break;
		case 'object':
			if ( prop.properties ) {
				let type = 'array{';
				for ( const subKey in prop.properties ) {
					const subRequiredMarker = prop.required && prop.required.includes( subKey ) ? '' : '?';
					const sub = prop.properties[subKey];

					type += `
\t *${indentation}   ${subKey}${subRequiredMarker}: ${mapType( sub, true, schema, level + 1 )},`;
				}
				type += `
\t *${indentation} }`;
				returnType = type;
			} else if ( prop.additionalProperties?.type ) {
				returnType = `array<string, ${mapType( prop.additionalProperties, true, schema, level )}>`;
			} else {
				returnType = 'array<string, mixed>';
			}
			break;
		default:
			returnType = getPHPType( type );
			break;
	}

	return `${requiredMarker}${returnType}`;
}

/**
 * @param {object} prop
 * @param {object} schema
 * @returns {object}
 */
function resolveRef( prop, schema ) {
	if ( ! prop.$ref ) {
		return prop;
	}

	if ( prop.$ref.startsWith( '#/definitions/' ) ) {
		const definition = prop.$ref.replace( '#/definitions/', '' );
		return schema.definitions[definition] || prop;
	}

	return prop;
}

/**
 * @param {string} type
 * @returns {string}
 */
function getPHPType( type ) {
	switch ( type ) {
		case 'string':
			return 'string';
		case 'null':
			return 'null';
		case 'number':
			return 'float';
		case 'integer':
			return 'int';
		case 'boolean':
			return 'bool';
		case 'array':
		case 'object':
			return 'array';
		default:
			return `'${type}'`;
	}
}
