<?php declare(strict_types = 1);
/**
 * This file is generated by the generate.mjs script.
 * Do not edit it manually.
 */

/**
 * QM_Data_Raw_Request_Response data object.
 *
 * @package query-monitor
 */

/**
 * @implements \ArrayAccess<string,mixed>
 */
class QM_Data_Raw_Request_Response implements \ArrayAccess {
	use QM_ArrayAccess;

	/**
	 * @var int|null
	 */
	public $status;

	/**
	 * @var array<string, string>
	 */
	public $headers;
}
