<?php declare(strict_types = 1);
/**
 * This file is generated by the generate.mjs script.
 * Do not edit it manually.
 */

/**
 * QM_Data_Raw_Request_Request data object.
 *
 * @package query-monitor
 */

/**
 * @implements \ArrayAccess<string,mixed>
 */
class QM_Data_Raw_Request_Request implements \ArrayAccess {
	use QM_ArrayAccess;

	/**
	 * @var string
	 */
	public $ip;

	/**
	 * @var string
	 */
	public $method;

	/**
	 * @var string
	 */
	public $scheme;

	/**
	 * @var string
	 */
	public $host;

	/**
	 * @var string
	 */
	public $path;

	/**
	 * @var string
	 */
	public $query;

	/**
	 * @var string
	 */
	public $url;

	/**
	 * @var array<string, string>
	 */
	public $headers;
}
