# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Acceptance Tests
on:
  push:
    branches:
      - 'develop'
      - 'trunk'
    paths:
      - '.github/workflows/acceptance-tests.yml'
      - 'tests/acceptance/**'
      - '**.css'
      - '**.js'
      - '**.php'
      - '**.tsx'
      - 'composer.json'
      - 'docker-compose.yml'
      - 'package.json'
      - 'tsconfig.json'
      - 'vite.config.js'
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/workflows/acceptance-tests.yml'
      - 'tests/acceptance/**'
      - '**.css'
      - '**.js'
      - '**.php'
      - '**.tsx'
      - 'composer.json'
      - 'docker-compose.yml'
      - 'package.json'
      - 'tsconfig.json'
      - 'vite.config.js'
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  test:
    name: WP ${{ matrix.wp }}
    permissions:
      contents: read
    strategy:
      # See the following for PHP compatibility of WordPress versions:
      # https://make.wordpress.org/core/handbook/references/php-compatibility-and-wordpress-versions/
      matrix:
        include:
          # Latest:
          - wp: '7.0'
            php: '8.5'
          - wp: '7.0'
            php: '7.4'
          # Latest -1:
          - wp: '6.9'
            php: '8.5'
          - wp: '6.9'
            php: '7.4'
          # Latest -2:
          - wp: '6.8'
            php: '8.4'
          - wp: '6.8'
            php: '7.4'
          # Oldest supported:
          - wp: '6.2'
            php: '8.2'
          - wp: '6.2'
            php: '7.4'
      fail-fast: false
    uses: johnbillion/plugin-infrastructure/.github/workflows/reusable-acceptance-tests.yml@cc47e37177c694e00b901a5dc89fda5644bc550f # 2.9.1
    with:
      node: true
      php: ${{ matrix.php }}
      wp: ${{ matrix.wp }}
