# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Build
on:
  push:
    branches:
      - 'release'
  workflow_dispatch:

permissions: {}

jobs:
  build:
    name: Build
    uses: szepeviktor/plugin-infrastructure/.github/workflows/reusable-build.yml@ee219e0c2c7b41b54aed9058551347abbe777ed4
    permissions:
      contents: write
    with:
      node: true
      tag: ${{ github.event_name != 'workflow_dispatch' }}
      vendor: true
