# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Build
on:
  push:
    branches:
      - 'release'
  workflow_dispatch:

permissions: {}

jobs:
  build:
    name: Build
    uses: johnbillion/plugin-infrastructure/.github/workflows/reusable-build.yml@e5acf0c698604c5a6fda78b8e7b45c4941a4a24e # 2.9.8
    permissions:
      contents: write # Required to push release branch and tags
    with:
      node: true
      tag: ${{ github.event_name != 'workflow_dispatch' }}
      vendor: true
