# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Build
on:
  push:
    branches:
      - 'release'
  workflow_dispatch:

permissions: {}

jobs:
  build:
    name: Build
    uses: johnbillion/plugin-infrastructure/.github/workflows/reusable-build.yml@1bf8b2cc9ee7211d0ac2e5d7f82bc9a151d7d094 # 2.7.2
    permissions:
      contents: write
    with:
      node: true
      tag: ${{ github.event_name != 'workflow_dispatch' }}
      vendor: true
