# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Deploy Tag
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: The version number of the release

concurrency: WordPress.org

permissions: {}

jobs:
  deploy:
    name: Deploy Tag
    if: github.event_name == 'workflow_dispatch' || github.event.release.prerelease == false
    uses: johnbillion/plugin-infrastructure/.github/workflows/reusable-deploy-tag.yml@bb606d520dfe6131697c80bfe0f4eabc7b8a46a6 # 2.8.0
    permissions:
      contents: write
      issues: write
      pull-requests: write
      attestations: write
      id-token: write
    with:
      deploy: ${{ github.event_name != 'workflow_dispatch' }}
      plugin: query-monitor
      readme: readme.txt
      version: ${{ github.event_name != 'workflow_dispatch' && github.event.release.tag_name || github.event.inputs.version }}
      username: johnbillion
    secrets:
      WPORG_SVN_PASSWORD: ${{ secrets.WPORG_SVN_PASSWORD }}
