# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Deploy Tag
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: The version number of the release

concurrency:
  group: WordPress.org
  cancel-in-progress: false

permissions: {}

jobs:
  deploy:
    name: Deploy Tag
    if: github.event_name == 'workflow_dispatch' || github.event.release.prerelease == false
    uses: johnbillion/plugin-infrastructure/.github/workflows/reusable-deploy-tag.yml@10408d3998889d780e8fbd593bc2d1e824496735
    permissions:
      contents: write      # Required to push the new branch
      issues: write        # Required for write access to milestones
      pull-requests: write # Required to create the pull request
      attestations: write  # Required to store the build provenance attestation
      id-token: write      # Required for creating an OIDC token for build provenance attestation
    with:
      deploy: ${{ github.event_name != 'workflow_dispatch' }}
      plugin: query-monitor
      readme: readme.txt
      version: ${{ github.event_name != 'workflow_dispatch' && github.event.release.tag_name || github.event.inputs.version }}
      username: johnbillion
    secrets:
      WPORG_SVN_PASSWORD: ${{ secrets.WPORG_SVN_PASSWORD }}
