# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Deploy Assets
on:
  push:
    branches:
      - deploy

permissions: {}

jobs:
  wordpress:
    name: WordPress.org
    permissions:
      contents: read
    uses: johnbillion/plugin-infrastructure/.github/workflows/reusable-deploy-assets.yml@e5acf0c698604c5a6fda78b8e7b45c4941a4a24e # 2.9.8
    with:
      plugin: query-monitor
      readme: readme.txt
      username: johnbillion
    secrets:
      WPORG_SVN_PASSWORD: ${{ secrets.WPORG_SVN_PASSWORD }}
