# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Integration Tests
on:
  push:
    branches:
      - 'develop'
      - 'trunk'
    paths:
      - '.github/workflows/integration-tests.yml'
      - 'tests/integration/**'
      - '**.php'
      - 'phpunit.xml.dist'
      - 'composer.json'
      - 'docker-compose.yml'
      - 'package.json'
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/workflows/integration-tests.yml'
      - 'tests/integration/**'
      - '**.php'
      - 'phpunit.xml.dist'
      - 'composer.json'
      - 'docker-compose.yml'
      - 'package.json'
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  test:
    name: WP ${{ matrix.wp }}
    permissions:
      contents: read
    uses: johnbillion/plugin-infrastructure/.github/workflows/reusable-integration-tests.yml@e5acf0c698604c5a6fda78b8e7b45c4941a4a24e # 2.9.8
    strategy:
      # See the following for PHP compatibility of WordPress versions:
      # https://make.wordpress.org/core/handbook/references/php-compatibility-and-wordpress-versions/
      matrix:
        include:
          # Latest:
          - wp: '7.1'
            php: '8.5'
          - wp: '7.1'
            php: '7.4'
          # Latest -1:
          - wp: '7.0'
            php: '8.5'
          - wp: '7.0'
            php: '7.4'
          # Latest -2:
          - wp: '6.9'
            php: '8.4'
          - wp: '6.9'
            php: '7.4'
          # Oldest supported:
          - wp: '6.3'
            php: '8.2'
          - wp: '6.3'
            php: '7.4'
      fail-fast: false
    with:
      php: ${{ matrix.php }}
      wp: ${{ matrix.wp }}
