# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Static Analysis
on:
  push:
    branches:
      - 'develop'
      - 'trunk'
      - 'client-side-rendering-feature'
    paths:
      - '.github/workflows/static-analysis.yml'
      - '**.php'
      - 'composer.json'
      - 'phpstan.neon.dist'
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/workflows/static-analysis.yml'
      - '**.php'
      - 'composer.json'
      - 'phpstan.neon.dist'
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.label }}
    permissions:
      contents: read
    uses: johnbillion/plugin-infrastructure/.github/workflows/reusable-static-analysis.yml@1bf8b2cc9ee7211d0ac2e5d7f82bc9a151d7d094 # 2.7.2
    strategy:
      matrix:
        label:
          - 'PHP'
        php:
          - '8.3'
          - '7.4'
      fail-fast: false
    with:
      php: ${{ matrix.php }}
