# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Static Analysis
on:
  push:
    branches:
      - 'develop'
      - 'trunk'
    paths:
      - '.github/workflows/static-analysis.yml'
      - '**.php'
      - 'composer.json'
      - 'phpstan.neon.dist'
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/workflows/static-analysis.yml'
      - '**.php'
      - 'composer.json'
      - 'phpstan.neon.dist'
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.label }}
    permissions:
      contents: read
    uses: johnbillion/plugin-infrastructure/.github/workflows/reusable-static-analysis.yml@d9a465cfe7c3e582d8712658ff653cc9e259f1ba # 2.9.6
    strategy:
      matrix:
        label:
          - 'PHP'
        php:
          - '8.5'
          - '7.4'
      fail-fast: false
    with:
      php: ${{ matrix.php }}
