# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Verify Plugin Distribution
on:
  schedule:
    # Once per hour
    #
    #        ┌───────────── minute           (0 - 59)
    #        │  ┌────────── hour             (0 - 23)
    #        │  │  ┌─────── day of the month (1 - 31)
    #        │  │  │  ┌──── month            (1 - 12 or JAN-DEC)
    #        │  │  │  │  ┌─ day of the week  (0 - 6 or SUN-SAT)
    #        │  │  │  │  │
    #        │  │  │  │  │
    #        │  │  │  │  │
    - cron: '0  *  *  *  *'
  push:
    branches:
      - 'develop'
    paths:
      - '.github/workflows/verify-distribution.yml'
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/workflows/verify-distribution.yml'
  workflow_dispatch:

permissions: {}

jobs:
  verify:
    name: Verify Plugin Distribution
    permissions: {}
    uses: johnbillion/plugin-infrastructure/.github/workflows/reusable-verify-distribution.yml@3141ee7813718d59c2d4df6d3d94f69a1becc951 # 1.1.0
    with:
      plugin: query-monitor
      owner: johnbillion
